### ISSUE TITLE
mark codecov check as optional

### ISSUE THREAD

**Issue by Akasurde** [ansible/event-driven-ansible#255]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/ansible-rulebook/issues) for duplicates.
- [X] I understand that event-driven-ansible collection is open source software provided for free and that I might not receive a timely response.

### Bug Summary

mark codecov check as optional 

### Environment

NA

### Steps to reproduce

NA

### Actual results

CI check fails after failure in codecov upload failures

### Expected results

Mark codecov CI check as optional since there will be failures in upload

**Comment by ssbarnea** [comment]
I will close this because this is not needed or desired and I will explain why:

- Codecov upload is now happening only from inside `check` jobs (single unified upload), lower change to fail
- Check job itself is designed to be idempotent, so you (or any project member) can retry them if it fails without having to rerun its dependencies that are producing the artifacts.
- Having checks optional is very dangerous, as it might allow accidental slips. It is less risky to just use admin power to bypass checks when really needed.
- Note that codecov themselves are planning to implement a retry mechanism in the uploader, so that will make it even more reliable.
- For the xunit uploading, we already have retry mechanism (coactions are maintained by myself).
