### ISSUE TITLE
EDA rulebook automatically capitalize the first letter of the key in the headers of webhook

### ISSUE THREAD

**Issue by MeCRO-DEV** [ansible/event-driven-ansible#368]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/ansible-rulebook/issues) for duplicates.
- [X] I understand that event-driven-ansible collection is open source software provided for free and that I might not receive a timely response.

### Bug Summary

A webhook has a key-value pair in the header: "os" = "linux". When the EDA controller receives it, it automatically converts the key to "Os".

### Environment

AAP2.5

### Steps to reproduce

1. Create a webhook in Jfrog with customized header: "os" = "linux", and configure a rulebook in EDA
2. Send a test webook from jfrog
3. You can see the header key has been changed to "Os" from debugging message.

### Actual results

The key "os" is modified and changed to "Os"

### Expected results

The key shouldn't be modified

**Comment by Alex-Izquierdo** [comment]
Hello @MeCRO-DEV. I can not reproduce the issue with the webhook plugin, but I can reproduce it with an event stream in eda-server. I assume the issue is not related with the collection but with [eda-server](https://github.com/ansible/eda-server), please, file the bug in that project or provide more concrete instructions to reproduce the issue, like the content of the rulebook, the version of ansible-rulebook and eda-server used and an example payload. 

We don't provide support for commercial subscriptions of Ansible Automation Platform, in that case please contact with your Red Hat Support.

**Comment by Alex-Izquierdo** [comment]
Hello again @MeCRO-DEV 
After further investigation I can confirm that our webhook plugin has the same behavior. 
Http headers are case insensitive. 

Refs:
https://datatracker.ietf.org/doc/html/rfc7230#section-3.2
https://datatracker.ietf.org/doc/html/rfc2068#section-4.2

Most of the http servers and clients normalize the headers by capitalization. This is not part of the standard but a widely adopted convention. It's done by cpython as well as by requests library and aiohttp library, the libraries that we use in eda-server and eda collection. 

You can ask to Jfrog to adhere to this convention or adapt your rulebooks to assume capitalization for headers, since you can be sure they will be capitalized in the context of ansible.eda.webhook or event streams. 

I consider this is not a bug.
